### ISSUE TITLE
ios build error

### ISSUE THREAD

**Issue by snapxtp** [alwx/react-native-http-bridge#20]
.../node_modules/react-native-http-bridge/ios/RCTHttpServer.h:1:9: 'React/RCTBridgeModule.h' file not found

**Comment by hamzauzumcu** [comment]
how did you solved this?

**Comment by hamzauzumcu** [comment]
https://github.com/f111fei/react-native-unity-view/issues/139#issuecomment-545289463

![Screen Shot 2019-12-24 at 7 49 23 PM](https://user-images.githubusercontent.com/11097112/71420475-94137e00-2686-11ea-81c8-a0b4c06198ae.png)

fixed.

**Comment by arys** [comment]
> $(SRCROOT)/../../../ios/Pods/Headers/Public

Hello @hamzauzumcu, I tried this and it causes other errors, like: 'limits' file not found

<img width="280" alt="Screen Shot 2021-05-14 at 17 05 54" src="https://user-images.githubusercontent.com/20532573/118262467-c53c5a80-b4d6-11eb-8b50-a3beb7abb00d.png">

**Comment by arys** [comment]
I ended up using this fork, works great https://github.com/digio/react-native-http-bridge
